### ISSUE TITLE
[1.16] Rendering crash in JEI

### ISSUE THREAD

**Issue by bangplaysgames** [Draconic-Inc/Draconic-Evolution#1652] opened 2022-04-19 13:55 UTC
## Base information
* Minecraft version: 1.16.5
* Mod version: 30.0.22.444
* Minecraft Forge version:  36.2.34
* Mod Pack: (if applicable)  Custom

### Crash report
https://controlc.com/037fb516

### Description / steps to reproduce

In a large custom modpack, I am getting a rendering crash when navigating to the pages containing draconic evolution items.  I'm unsure which item is causing the crash.  I have attached the crashlog via controlc.com.

*EDIT*
No custom rendering mods such as optifine are installed except Flywheel, which is a dependency for Create.

**Comment by FoxMcloud5655** [comment] 2022-04-19 14:24
Duplicate of #1603, #1643, #1651.  Same solution applies.

**Closed by FoxMcloud5655** 2022-04-19 14:24 UTC
Labels: bug, 1.16
