### ISSUE TITLE
[1.20.1] Incompatibility with Oculus

### ISSUE THREAD

**Issue by caiucaindo** [Draconic-Inc/Draconic-Evolution#1846] opened 2024-11-08 05:04 UTC
## Base information
* Minecraft version: 1.20.1
* Mod version: lastest
* Minecraft Forge version: 47.2.20

When playing with Oculus and Draconic Revolution, almost all Draconic tools become invisible in third-person view or when dropped on the ground. They can only be seen when held in the first-person view. Even if no shaders or configurations are active in Oculus, this bug persists just by having both mods in the game. Since Oculus is one of the most used mods, I believe it would be a great benefit to seek a resolution for this.

**Comment by FoxMcloud5655** [comment] 2024-11-08 05:26
Duplicate of #1842.  Oculus is the one that needs to fix this, not Draconic Evolution.

**Closed by FoxMcloud5655** 2024-11-08 05:26 UTC
Labels: bug
