### ISSUE TITLE
[1.20.1] EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by oskarbukovsky** [Draconic-Inc/Draconic-Evolution#1828] opened 2024-08-15 19:02 UTC
## Base information
* Minecraft version: 1.20.1
* Mod version: 3.1.2.583
* Minecraft Forge version: 47.3.5
* Mod Pack: [Modpack](https://www.curseforge.com/minecraft/modpacks/tech-craft-neobox)

### Crash report
Crashing player logs and java crash:
[latest-with-crash.log](https://github.com/user-attachments/files/16629129/latest-with-crash.log)
[hs_err_pid1280.log](https://github.com/user-attachments/files/16629131/hs_err_pid1280.log)
My working latest.log:
[latest-working.log](https://github.com/user-attachments/files/16629130/latest-working.log)

Another player crashing logs:
[hs_err_pid133036.log](https://github.com/user-attachments/files/16629163/hs_err_pid133036.log)
[2024-07-25-1.log](https://github.com/user-attachments/files/16629164/2024-07-25-1.log)

Next crashing player crashes:
[1723044990092.log](https://github.com/user-attachments/files/16629184/1723044990092.1.log)
[1723059595444.log](https://github.com/user-attachments/files/16629186/1723059595444.1.log)

### Description / steps to reproduce
Install modpack with amd gpu and wait for crash

**Comment by FoxMcloud5655** [comment] 2024-08-16 00:29
Duplicate of #1825.

**Closed by FoxMcloud5655** 2024-08-16 00:29 UTC
Labels: bug
