### ISSUE TITLE
[1.16] <My game is crashing when my friend goes next to me wearing the chestplate or when I open the mod page on jei and bug with the armor>

### ISSUE THREAD

**Issue by goncaloaa** [Draconic-Inc/Draconic-Evolution#1787] opened 2024-06-14 21:23 UTC
## Base information
* Minecraft version: 1.16.5
* Mod version: 1.16.5 3.0.29.528 (i think its this)
* Minecraft Forge version: 36.2.42
* Mod Pack: i made this one

### Crash report
Crash 1: https://pastebin.com/bcck9YC5
Crash 2: https://pastebin.com/qTdzprR9

### Description 
I sent two crash reports, the first one happened when I was playing with my friend, he made a Chest Piece and when he got near me, my game simply closed, we tried multiple times and it always crashed.
The second report happened when we were trying to figure it out, I was alone in the world and searched the mod page on JEI so I could grab the armor myself, when I searched, it crashed.
I already tried loading the game without optifine and it stays the same.
Also, when my friend uses the chest piece along with a jetpack from Mekanism, I can see him through walls, it doesn't affect performance or anything, just a bug that maybe doesn't have anything to do with Draconic, just thought I should mention it, also sending a print screen.
![2024-06-14_17 11 02](https://github.com/Draconic-Inc/Draconic-Evolution/assets/172854495/08c86017-d092-47fb-94e5-cbeaadef948c)
.
Please help

**Comment by FoxMcloud5655** [comment] 2024-06-14 21:33
Duplicate of #1597.

**Closed by FoxMcloud5655** 2024-06-14 21:33 UTC
Labels: bug, 1.16
