### ISSUE TITLE
[1.16] < Crash when i search '@draconic' in JEI >

### ISSUE THREAD

**Issue by WayanD157** [Draconic-Inc/Draconic-Evolution#1779] opened 2024-03-01 04:13 UTC
## Base information
* Minecraft version: 1.16.5
* Mod version: Last Version ( Draconic-Evolution-1.16.5-3.0.29.518-universal )
* Minecraft Forge version: 36.2.34
* Mod Pack: (Mine -  I didn't edit the mods or anything, I just downloaded them and put them in the mods folder)

### Crash report

https://pastebin.com/KkmKJHNw

**Comment by FoxMcloud5655** [comment] 2024-03-01 04:25
Duplicate of #1597.

**Closed by FoxMcloud5655** 2024-03-01 04:25 UTC
Labels: bug, 1.16
