### ISSUE TITLE
[1.16] Game crashes instantly upon joining world with a Wyvern Sword in inventory

### ISSUE THREAD

**Issue by emilydaemon** [Draconic-Inc/Draconic-Evolution#1782] opened 2024-04-27 06:01 UTC
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.29.518
* Minecraft Forge version: 36.2.42
* Mod Pack: Custom, I'll send the full mod list upon request

### Crash report

There was no `/crash-reports/crash-<date and time of crash>.txt`, instead, a `hs_err_pid<process ID>.log`, which from my understanding, means a fatal error in the Java Runtime Environment, which is much more serious than just Minecraft crashing.

In any case, here's a link to the hs_err: https://mclo.gs/H5mxpS6

### Description / steps to reproduce

This happened on multiplayer, not sure if it happens on singleplayer or not.

Having a Wyvern Sword in the 7th slot of your inventory can effectively ban you from a server. 
To be able to re-join, you need a server administrator to remove the Wyvern Sword from your inventory with an NBT editor.
This might also happen with the sword in a different slot, but I haven't tested that.

This happens regardless of modules or enchantments.

Steps to reproduce:

1. Add a Wyvern Sword to the 7th slot in your inventory.
2. Exit the game and rejoin.
3. Crash!

If any more information is required, please let me know.

**Comment by FoxMcloud5655** [comment] 2024-04-27 08:57
Duplicate of #1597.

**Closed by FoxMcloud5655** 2024-04-27 08:57 UTC
Labels: bug, 1.16
