### ISSUE TITLE
[1.16] Crash only on AMD graphics cards

### ISSUE THREAD

**Issue by OverKot** [Draconic-Inc/Draconic-Evolution#1749] opened 2023-08-16 12:03 UTC
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.28.500-universal
* Minecraft Forge version: 36.2.34
* Mod Pack: Gloomy Rise ( by LGame Studio )

### Crash report
[hs_err_pid10168.log](https://github.com/Draconic-Inc/Draconic-Evolution/files/12359103/hs_err_pid10168.log)
[Console.txt](https://github.com/Draconic-Inc/Draconic-Evolution/files/12359104/Console.txt)

### Description / steps to reproduce

Crashes if you turn on the tab with quests ( hi-tech ), or if you just click on the page with the mod in the creative

i5 11400f + rx 6800

**Comment by OverKot** [comment] 2023-08-16 12:14
https://github.com/Draconic-Inc/Draconic-Evolution/assets/58006439/f9047eab-8e2c-48e0-bff7-759a5831ca2c

https://github.com/Draconic-Inc/Draconic-Evolution/assets/58006439/b3698570-b3b7-4dfe-98f2-cad348f0969b

**Comment by FoxMcloud5655** [comment] 2023-08-16 14:33
Duplicate of #1597.

**Closed by FoxMcloud5655** 2023-08-16 14:33 UTC
Labels: bug, 1.16
