### ISSUE TITLE
Weird Redstone glitch when two timers are hooked up to two different fusion crafters in the same chunk

### ISSUE THREAD

**Issue by coaber** [Draconic-Inc/Draconic-Evolution#1719] opened 2023-02-22 06:41 UTC
I was messing around with automated fusion this morning, and next to my main fusion crafter, i placed another setup for automated awakened draconium fusion. Both setups had a timer hooked up for automated cycles, however once both ticked the block, and one was running the fusion process, it would keep turning off and on as if the block was entangled to the other timer. This however only happened if both timers were in the *same* chunk. Down below i attached a video of the glitch ocurring for more context. 

Using FML 40.1.84
DE 3.0.27.515 
BC 3.1.7.276

[https://youtu.be/gmE_p6UQL5o](url)

**Comment by FoxMcloud5655** [comment] 2023-02-22 12:39
Duplicate of #1668.  Update your mods.

**Closed by FoxMcloud5655** 2023-02-22 12:39 UTC
