### ISSUE TITLE
[1.12] Can't craft within the fusion crafting core

### ISSUE THREAD

**Issue by NZombified** [Draconic-Inc/Draconic-Evolution#1729] opened 2023-04-02 13:34 UTC
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2
* Minecraft Forge version: 1.12.2
* Mod Pack: InsaneCraft Modpack by SparkUniverse_

### Crash report
https://pastebin.com/7vncyJz4

**Comment by FoxMcloud5655** [comment] 2023-04-02 14:00
Can't do anything without a crash report.  Also, no DE version exists that's labeled "1.12.2".

**Comment by NZombified** [comment] 2023-04-02 14:07
> Can't do anything without a crash report. Also, no DE version exists that's labeled "1.12.2".

My bad, I accidentally put the .2, I've been running 1.12.

**Comment by NZombified** [comment] 2023-04-11 19:47
> Can't do anything without a crash report. Also, no DE version exists that's labeled "1.12.2".

I responded about a week ago now, is there going to be any other comment about this?  This keeps happening throughout all my worlds and I'm not sure if it's because of a mod file or what.

**Comment by FoxMcloud5655** [comment] 2023-04-11 20:33
When you first responded, it had nothing useful in it.  No notifications are ever sent out for edits.

Try downloading and using VanillaFix.  I don't think that's the real issue here, but it's worth a shot.

**Comment by NZombified** [comment] 2023-04-11 20:34
> When you first responded, it had nothing useful in it. No notifications are ever sent out for edits.
> 
> Try downloading and using VanillaFix. I don't think that's the real issue here, but it's worth a shot.

Yeah I already got VanillaFix in the modpack.  First time using github, didn't know there were no notifications, my bad.  I've been kind of frustrated about this for about a month now and I really like DE so I'm kind of eager to fix this.

**Comment by FoxMcloud5655** [comment] 2023-04-12 04:00
No, the crash report is enough.  It's something to do with Project Intelligence not being able to download something, so this is really an issue that should be pasted over there.

1.12.2 is an unsupported version, but I'll still look into this later and see if it's a quick fix.

**Comment by NZombified** [comment] 2023-04-12 04:05
> No, the crash report is enough. It's something to do with Project Intelligence not being able to download something, so this is really an issue that should be pasted over there.
> 
> 1.12.2 is an unsupported version, but I'll still look into this later and see if it's a quick fix.

Okay perfect, thank you so much, I appreciate it.

**Comment by artem-chornyi** [comment] 2023-07-06 11:56
Base information

Mod pac: Enigmatica 2: Light
Draconic-Evolution-1.12.2-2.3.27.353-universal.jar

Hello @FoxMcloud5655, I also encountered this problem, I can not connect energy, the main problem is that the Fusion Crafting Injector has 0/0 energy.
I see that you are not currently developing this version, but perhaps this will be a quick fix for this bug?)
Or perhaps something needs to be done on my part?
<img width="1151" alt="Снимок экрана 2023-07-06 в 14 52 28" src="https://github.com/Draconic-Inc/Draconic-Evolution/assets/83292981/ad3f73e9-9ea4-4d82-ae4d-9423a6fb43c7">

**Comment by FoxMcloud5655** [comment] 2023-07-06 12:19
That's a completely separate issue.  You really need to make a new issue if it has nothing to do with the original.  That being said, that's not a bug.  The injector doesn't hold energy until you start a recipe, because it doesn't know how much RF is going to be needed.  In order to keep the charging time the same across all recipes, the RF/t you can input and the maximum it can hold both change per recipe.

**Comment by artem-chornyi** [comment] 2023-07-06 12:37
@FoxMcloud5655  Thank you very much for the quick answer, soy mistake was that there was a distance of 2 blocks, now everything works fine)

Have a good day)

**Comment by NZombified** [comment] 2023-07-17 21:20
> No, the crash report is enough. It's something to do with Project Intelligence not being able to download something, so this is really an issue that should be pasted over there.
> 
> 1.12.2 is an unsupported version, but I'll still look into this later and see if it's a quick fix.

Any update on this yet?

**Comment by FoxMcloud5655** [comment] 2023-07-17 23:36
Oh, sorry.  No, there's not much that's being done in terms of development on either my or Brandon's side right now.  If someone else finds the issue and can solve it, awesome.  Brandon can make a pull request.

Aside from that though, I remember looking at it and not being able to quickly find anything wrong with it.  All of the focus (what's left in MC modding right now) is on 1.20.x for the time being.

**Comment by NZombified** [comment] 2023-07-20 12:40
> Oh, sorry. No, there's not much that's being done in terms of development on either my or Brandon's side right now. If someone else finds the issue and can solve it, awesome. Brandon can make a pull request.
> 
> Aside from that though, I remember looking at it and not being able to quickly find anything wrong with it. All of the focus (what's left in MC modding right now) is on 1.20.x for the time being.

Alright, thanks for not taking up too much of my time on this!

**Comment by FoxMcloud5655** [comment] 2024-07-06 00:59
Closing out an old issue.

**Closed by FoxMcloud5655** 2024-07-06 00:59 UTC
Labels: bug, 1.12
