### ISSUE TITLE
[Feature Request] Port over to 1.19.2

### ISSUE THREAD

**Issue by MarquesCoding** [Draconic-Inc/Draconic-Evolution#1756] opened 2023-10-01 12:16 UTC
CodeChicken Lib has updated to 1.19.2, is Draconic going to upgrade anytime soon?

**Comment by FoxMcloud5655** [comment] 2023-10-01 13:07
Duplicate of #1752.

**Closed by FoxMcloud5655** 2023-10-01 13:07 UTC
Labels: enhancement

**Comment by FoxMcloud5655** [comment] 2023-10-01 13:09
Additional info posted in the duplicate.
