### ISSUE TITLE
[Feature Request] DE copy button or tool 1.20.1

### ISSUE THREAD

**Issue by RenanPlay13013** [Draconic-Inc/Draconic-Evolution#1820] opened 2024-08-04 17:02 UTC
make a function to copy the Fusion Crafting Recipe JSON file of datapack, making it so that newbies in the field can use this excellent recipe method, making DE recipe alternatives more common in modpacks and coding many DE recipes is not very pleasant.

**Comment by FoxMcloud5655** [comment] 2024-08-04 19:49
Duplicate of #1819.

**Closed by FoxMcloud5655** 2024-08-04 19:49 UTC
Labels: enhancement
