### ISSUE TITLE
[1.16] Upgrading Wyvern Capacitor to Draconic Deletes modules

### ISSUE THREAD

**Issue by MissionArcher** [Draconic-Inc/Draconic-Evolution#1686] opened 2022-10-02 19:39 UTC
## Base information
* Minecraft version: 1.16.5
* Mod version: Draconic-Evolution-1.16.5-3.0.27.462-universal
* Minecraft Forge version: 36.2.39
* Mod Pack: N/A

### Crash report
(If applicable)

### Description / steps to reproduce

Put modules into Wyvern Capacitor
Upgrade to Draconic Capacitor using the Fusion Crafter
Modules disappear

**Comment by FoxMcloud5655** [comment] 2022-10-02 20:03
Duplicate of #1661.

**Comment by MissionArcher** [comment] 2022-10-02 20:26
I don't belive that these two issues are related
I think this is down to the fact that the Wyvern Module doesn't go in the Fusion Crafting Core like all the other equipment that lacks this issue
![image](https://user-images.githubusercontent.com/72813822/193474769-f741b7cd-2eb3-4b3f-9ee8-d1855ea19b13.png)

**Comment by FoxMcloud5655** [comment] 2022-10-03 02:40
My bad; I misread your title.  This is known and has been reported on Discord multiple times.

**Comment by FoxMcloud5655** [comment] 2022-11-19 05:11
Fixed in [8fc2fd92](https://github.com/Draconic-Inc/Draconic-Evolution/commit/8fc2fd92d6becf705c71dbcd6b1b0f55e80b0dd7).

**Closed by FoxMcloud5655** 2022-11-19 05:11 UTC
Labels: bug, 1.16
